from tlsfinder._aggr import plot_spatial_clusters_by_slice
from tlsfinder._group import plot_spatial_clusters_by_slice, plot_enrichment
from tlsfinder._nhood import plot_spatial_score_or_neighbors
from tlsfinder._tls import plot_tls_blocks_on_HE, plot_tls_blocks_labeled